on:
  push:
    branches: [ main, staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build static site
        run: |
          npm ci
          npm run generate
      - name: Set bucket name
        run: |
          [ "${{ github.ref }}" == "refs/heads/main" ] && echo "volcode.org-bucket" || echo "staging.volcode.org-bucket"
      - name: Sync to S3
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          BUCKET=$(./scripts/set-bucket-name.sh)
          aws s3 sync ./dist s3://$BUCKET --delete
      - name: Invalidate CloudFront
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            DIST_ID=$(terraform output -raw cloudfront_urls["volcode.org_id"])
          else
            DIST_ID=$(terraform output -raw cloudfront_urls["staging.volcode.org_id"])
          fi
          aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"