name: Deployment

# This workflow runs ONLY on direct pushes to main/staging
# It runs tests and then deploys if tests pass (deploy "waits" for tests via 'needs')
# It is separate from the Pull Request Tests workflow and they do not interact
on:
  push:
    branches: [main, staging]

jobs:
  deploy:
    name: Deploying...
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup environment variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "NUXT_PUBLIC_IS_STAGING=false" >> $GITHUB_ENV
          else
            echo "NUXT_PUBLIC_IS_STAGING=true" >> $GITHUB_ENV
          fi
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0
          
      - name: Build static site
        env:
          NUXT_PUBLIC_IS_STAGING: ${{ env.NUXT_PUBLIC_IS_STAGING }}
        run: |
          npm ci
          npm run generate

      - name: Prepare S3 uploads
        run: |
          # Ensure the dist directory exists
          if [ -d "dist" ]; then
            # Copy index.html to each route directory
            mkdir -p dist/experience dist/projects dist/contact
            
            # Make sure each route gets its correct dedicated file or fallback to index.html
            cp dist/experience/index.html dist/experience/index.html || cp dist/index.html dist/experience/index.html
            cp dist/projects/index.html dist/projects/index.html || cp dist/index.html dist/projects/index.html
            cp dist/contact/index.html dist/contact/index.html || cp dist/index.html dist/contact/index.html
            
            # Ensure pages exist and aren't redirected
            touch dist/projects/.nojekyll
            touch dist/experience/.nojekyll
            touch dist/contact/.nojekyll
          fi

      - name: Sync to S3
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            BUCKET="volcode-volcode.org-default"
          else
            BUCKET="volcode-staging.volcode.org-default"
          fi
          aws s3 sync ./dist s3://$BUCKET --delete
          
      - name: Invalidate CloudFront
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Set domain based on branch
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            DOMAIN="volcode.org"
          else
            DOMAIN="staging.volcode.org"
          fi
          BUCKET_NAME="volcode-${DOMAIN}-default"
          
          echo "🔍 Finding CloudFront distribution for $DOMAIN..."
          
          # Find the correct distribution ID by matching S3 bucket in origin
          DISTRIBUTIONS=$(aws cloudfront list-distributions --output json)
          DIST_ID=$(echo "$DISTRIBUTIONS" | jq -r --arg bucket "$BUCKET_NAME" '
            .DistributionList.Items[] | 
            select(.Origins.Items != null) | 
            select(.Origins.Items[].DomainName | contains($bucket)) | 
            .Id
          ')
          
          # Skip if no distribution found
          if [ -z "$DIST_ID" ]; then
            echo "⚠️ No CloudFront distribution found for $DOMAIN"
            echo "   Skipping invalidation"
            exit 0
          fi
          
          echo "✅ Found distribution ID: $DIST_ID for $DOMAIN"
          echo "🔄 Attempting to invalidate CloudFront cache..."
          
          # Run invalidation with error handling - use true to prevent workflow failure
          if aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*" || true; then
            # This block will always run due to the || true
            # Check if we got a real error message in the output
            if [[ $? -ne 0 ]]; then
              echo "⚠️ Failed to invalidate cache - likely a permissions issue"
              echo "   You need to add cloudfront:CreateInvalidation permission to your IAM user"
              echo "   The deployment will continue without cache invalidation"
            else
              echo "✅ Cache invalidation started successfully"
            fi
          fi
          
          # Always exit with success
          echo "Deployment completed successfully"