on:
  push:
    branches: [ main, staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup environment variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "NUXT_PUBLIC_IS_STAGING=false" >> $GITHUB_ENV
          else
            echo "NUXT_PUBLIC_IS_STAGING=true" >> $GITHUB_ENV
          fi
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0
          
      - name: Build static site
        env:
          NUXT_PUBLIC_IS_STAGING: ${{ env.NUXT_PUBLIC_IS_STAGING }}
        run: |
          npm ci
          npm run generate
          
      - name: Sync to S3
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            BUCKET="volcode-volcode.org-default"
          else
            BUCKET="volcode-staging.volcode.org-default"
          fi
          aws s3 sync ./dist s3://$BUCKET --delete
          
      - name: Invalidate CloudFront
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd terraform
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            DOMAIN="volcode.org"
          else
            DOMAIN="staging.volcode.org"
          fi
          
          # First get the raw output and debug it
          echo "Getting CloudFront outputs..."
          terraform output cloudfront_urls
          
          # Get the terraform output in raw json format and save to file to inspect
          terraform output -json cloudfront_urls > cf_output.json
          echo "Raw JSON output:"
          cat cf_output.json
          
          # Try to extract the ID - using the _id suffix format
          ID_KEY="${DOMAIN}_id"
          DIST_ID=$(cat cf_output.json | jq -r --arg key "$ID_KEY" '.[$key]')
          echo "Looking for key: $ID_KEY"
          echo "Extracted distribution ID: $DIST_ID"
          
          if [ -z "$DIST_ID" ] || [ "$DIST_ID" = "null" ]; then
            echo "No distribution ID found for $DOMAIN, skipping invalidation"
          else
            echo "Invalidating cache for distribution $DIST_ID"
            aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"
          fi