name: Pull Request Tests

on:
  pull_request:
    branches: [main, staging]

jobs:
  test:
    name: Validate PR
    runs-on: ubuntu-latest
    container: 
      image: node:20
    steps:
      - uses: actions/checkout@v3
      
      - name: Install All Packages
        run: npm ci
      
      - name: Run Tests
        run: npm test