name: Testing

# This workflow runs ONLY on pull requests to validate changes before merging
# It is completely separate from the CI/CD Pipeline that runs on push events
# They are independent and do not wait for each other
on:
  pull_request:
    branches: [main, staging]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container: 
      image: node:20
    steps:
      - uses: actions/checkout@v3
      
      - name: Install All Packages
        run: npm ci
      
      - name: Run Tests
        run: npm test